const express = require("express")
const router = express.Router()
const {validateToken} = require("../../auth/jwt")
const {insetLaptopDb,getAlllaptops,filterLaptopsonkeyterm,filterPricewise,filterHP,filterLenovo,filterApple,updateLaptop,updatepriceLaptop,countAlllaptops,countHPlaptops,countlenovoLaptops,countApple,deleteLaptop} = require("../../controllers/laptops/laptop")
router.post('/insert/laptop',validateToken,insetLaptopDb)
router.get('/get/alllaptops',getAlllaptops)
router.get('/filter/all',filterLaptopsonkeyterm)
router.get('/filter/pricewise',filterPricewise)
router.get('/filter/hp',validateToken,filterHP)
router.get('/filter/lenovo',validateToken,filterLenovo)
router.get('/filter/apple',validateToken,filterApple)
router.put('/update/availability',validateToken,updateLaptop)
router.put('/update/price',validateToken,updatepriceLaptop)
router.get('/count/alllaptops',countAlllaptops)
router.get('/count/hp',countHPlaptops)
router.get('/count/lenovo',countlenovoLaptops)
router.get('/count/apple',countApple)
router.delete('/delete/laptop',validateToken,deleteLaptop)
module.exports = router 